# -*- coding: utf-8 -*-
"""3-StatementScript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IUU2C0qevh61A5L0X8YfwZ3XmEgpRaI
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

ticker = yf.Ticker(input("Please input ticker:"))
income_stmt = ticker.financials
balance_sheet = ticker.balance_sheet
cash_flow = ticker.cashflow

def clean_statement(df):
    df = df.T.copy()
    df.index = pd.to_datetime(df.index).year
    df = df / 1e6
    return df
is_df = clean_statement(income_stmt).sort_index().iloc[-4:]
bs_df = clean_statement(balance_sheet).sort_index().iloc[-4:]
cf_df = clean_statement(cash_flow).sort_index().iloc[-4:]

def build_model(is_df, bs_df, cf_df):
    years = is_df.index

    model = pd.DataFrame(index=years)

    #Income
    model['Revenue']        = is_df.get('Total Revenue', np.nan)
    model['COGS']           = is_df.get('Cost Of Revenue', np.nan)
    model['Gross Profit']   = model['Revenue'] - model['COGS']
    model['OpEx']           = is_df.get('Operating Expense', np.nan)
    model['EBIT']           = is_df.get('EBIT', np.nan)
    model['Net Income']     = is_df.get('Net Income', np.nan)

    #Cash Flow
    model['Operating CF']   = cf_df.get('Operating Cash Flow', np.nan)
    model['Capex']          = cf_df.get('Capital Expenditure', np.nan)
    model['Free Cash Flow'] = model['Operating CF'] + model['Capex']  # capex is negative
    model['Financing CF']   = cf_df.get('Financing Cash Flow', np.nan)

    #Balance Sheet
    model['Cash']               = bs_df.get('Cash And Cash Equivalents', np.nan)
    model['Total Assets']       = bs_df.get('Total Assets', np.nan)
    model['Total Liabilities']  = bs_df.get('Total Liabilities Net Minority Interest', np.nan)
    model['Total Equity']       = bs_df.get('Stockholders Equity', np.nan)

    #Equation
    model['BS Check'] = model['Total Assets'] - (model['Total Liabilities'] + model['Total Equity'])

    return model

model = build_model(is_df, bs_df, cf_df)
print(model.round(1).to_string())

# Margins
model['Gross Margin']    = model['Gross Profit'] / model['Revenue']
model['Net Margin']      = model['Net Income']   / model['Revenue']
model['FCF Margin']      = model['Free Cash Flow'] / model['Revenue']

#Projection
rev_cagr = (model['Revenue'].iloc[-1] / model['Revenue'].iloc[0]) ** (1 / (len(model) - 1)) - 1
avg_net_margin  = model['Net Margin'].mean()
avg_fcf_margin  = model['FCF Margin'].mean()

future_years = [model.index[-1] + i for i in range(1, 4)]
future_rev   = [model['Revenue'].iloc[-1] * (1 + rev_cagr) ** i for i in range(1, 4)]

proj = pd.DataFrame({
    'Revenue':     future_rev,
    'Net Income':  np.array(future_rev) * avg_net_margin,
    'Free Cash Flow': np.array(future_rev) * avg_fcf_margin,
}, index=future_years)

print(f"\nRevenue CAGR: {rev_cagr:.1%}")
print(proj.round(1))

#Graph Setup
fig = plt.figure(figsize=(16, 10))
fig.suptitle("3-Statement Model — AAPL ($M)", fontsize=14, fontweight='bold')
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

hist_years = list(model.index)
proj_years = list(proj.index)
all_years  = hist_years + proj_years

def extend(metric, proj_df=None):
    h = list(model[metric].fillna(0))
    p = list(proj_df[metric].fillna(0)) if proj_df is not None and metric in proj_df else [np.nan] * 3
    return h + p

colors = {'hist': '#2196F3', 'proj': '#90CAF9'}

#Revenue/Net Income
ax1 = fig.add_subplot(gs[0, 0])
rev = extend('Revenue', proj)
ni  = extend('Net Income', proj)
bars = ax1.bar(all_years, rev, color=[colors['hist']] * len(hist_years) + [colors['proj']] * 3, label='Revenue')
ax1.plot(all_years, ni, 'o-', color='#E53935', label='Net Income', linewidth=2)
ax1.set_title('Revenue & Net Income')
ax1.set_ylabel('$M')
ax1.legend(fontsize=8)
ax1.tick_params(axis='x', rotation=45)

#Margin
ax2 = fig.add_subplot(gs[0, 1])
ax2.plot(hist_years, model['Gross Margin'] * 100, 's-', color='#4CAF50', label='Gross margin')
ax2.plot(hist_years, model['Net Margin'] * 100,   'o-', color='#FF9800', label='Net margin')
ax2.set_title('Margins (%)')
ax2.set_ylabel('%')
ax2.legend(fontsize=8)
ax2.tick_params(axis='x', rotation=45)

#FCF
ax3 = fig.add_subplot(gs[0, 2])
fcf = extend('Free Cash Flow', proj)
ax3.bar(all_years, fcf, color=[colors['hist']] * len(hist_years) + [colors['proj']] * 3)
ax3.set_title('Free Cash Flow')
ax3.set_ylabel('$M')
ax3.tick_params(axis='x', rotation=45)

plt.savefig('three_statement_model.png', dpi=150, bbox_inches='tight')
plt.show()